[WIP] perf/x86/amd: Fix op_model_amd build error
Fixes:

  CC [M]  arch/x86/oprofile/op_model_amd.o
arch/x86/oprofile/op_model_amd.c:48:12: error: static declaration of ‘ibs_caps’ follows non-static declaration
 static u32 ibs_caps;
            ^~~~~~~~
In file included from arch/x86/oprofile/op_x86_model.h:16,
                 from arch/x86/oprofile/op_model_amd.c:28:
./arch/x86/include/asm/perf_event.h:414:12: note: previous declaration of ‘ibs_caps’ was here
 extern u32 ibs_caps;
            ^~~~~~~~
scripts/Makefile.build:279: recipe for target 'arch/x86/oprofile/op_model_amd.o' failed
make[1]: *** [arch/x86/oprofile/op_model_amd.o] Error 1
Makefile:1805: recipe for target 'arch/x86/oprofile' failed
make: *** [arch/x86/oprofile] Error 2

This is because "[WIP] perf/x86/amd/ibs: Allow the driver to be built
as a module" had neglected to remove the original copy of ibs_caps,
which is what we do now.

Reported-by: Yazen Ghannam <yazen.ghannam@amd.com>
Signed-off-by: Kim Phillips <kim.phillips@amd.com>