[IN-REVIEW] KVM: SVM: Fix compilation issue due to svm_x86_ops
Fix the compilation error:
    arch/x86/kvm/svm/svm.c:1088:53: error: ‘svm_x86_ops’ undeclared (first use in this function);

which was introduced by commit 0584405f9917 ("KVM: SVM: Only call vcpu_(un)blocking when AVIC is enabled")

Signed-off-by: Suravee Suthikulpanit <suravee.suthikulpanit@amd.com>